import { ec as EC } from 'elliptic';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex, utf8ToBytes } from '@noble/hashes/utils.js';
import { canonicalStringify, JsonValue } from './canonicalJson';

const ec = new EC('p256');

/**
 * Service to cryptographically sign offline attendance records.
 * This guarantees to the backend that the record was generated by a genuine,
 * enrolled device, and not forged by a malicious API script.
 */
class CryptoSigner {
  private keyPair: any;

  constructor() {
    this.keyPair = ec.genKeyPair();
  }

  /**
   * Configure a persisted P-256 private key loaded from secure device storage.
   * The private key must be a 32-byte hex string.
   */
  public configurePrivateKey(privateKeyHex: string) {
    this.keyPair = ec.keyFromPrivate(privateKeyHex, 'hex');
  }

  public canonicalPayload(payload: JsonValue): string {
    return canonicalStringify(payload);
  }

  /**
   * Generates a DER-encoded ECDSA/SHA-256 signature compatible with the backend.
   */
  public signPayload(payload: string | JsonValue): string {
    const payloadString = typeof payload === 'string' ? payload : this.canonicalPayload(payload);
    const digestHex = bytesToHex(sha256(utf8ToBytes(payloadString)));
    const signature = this.keyPair.sign(digestHex, { canonical: true });

    return signature.toDER('hex');
  }

  /**
   * Get the public key in PEM format for /auth/device/register.
   */
  public getPublicKeyPem(): string {
    const publicPoint = this.keyPair.getPublic().encode('array', false);
    const spkiHeader = [
      0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
      0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
      0x42, 0x00,
    ];
    const derBytes = Uint8Array.from([...spkiHeader, ...publicPoint]);
    const base64 = this.base64Encode(derBytes);
    const body = base64.match(/.{1,64}/g)?.join('\n') ?? base64;

    return `-----BEGIN PUBLIC KEY-----\n${body}\n-----END PUBLIC KEY-----`;
  }

  private base64Encode(bytes: Uint8Array): string {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    let output = '';

    for (let i = 0; i < bytes.length; i += 3) {
      const a = bytes[i];
      const b = bytes[i + 1] ?? 0;
      const c = bytes[i + 2] ?? 0;
      const triplet = (a << 16) | (b << 8) | c;

      output += alphabet[(triplet >> 18) & 63];
      output += alphabet[(triplet >> 12) & 63];
      output += i + 1 < bytes.length ? alphabet[(triplet >> 6) & 63] : '=';
      output += i + 2 < bytes.length ? alphabet[triplet & 63] : '=';
    }

    return output;
  }
}

export const cryptoSigner = new CryptoSigner();
