import { ec as EC } from 'elliptic';

// In a real production deployment, this private key is generated once on the device
// and stored in the iOS Keychain or Android Keystore (e.g., via react-native-keychain).
// The corresponding public key is sent to the backend during device enrollment.
// For this Hackathon prototype, we use a static pre-enrolled test key.
const DEVICE_PRIVATE_KEY_HEX = "e045ab23... (omitted for brevity, use your generated key here)";

const ec = new EC('p256');

/**
 * Service to cryptographically sign offline attendance records.
 * This guarantees to the backend that the record was generated by a genuine,
 * enrolled device, and not forged by a malicious API script.
 */
class CryptoSigner {
  private keyPair: any;

  constructor() {
    try {
      // In prod, load from Secure Enclave / Keystore
      this.keyPair = ec.keyFromPrivate(DEVICE_PRIVATE_KEY_HEX, 'hex');
    } catch (e) {
      console.warn("Using ephemeral key for prototype (No static key found).");
      this.keyPair = ec.genKeyPair();
    }
  }

  /**
   * Generates an ECDSA signature for the given payload string.
   */
  public signPayload(payloadString: string): string {
    // 1. Hash the payload (typically SHA-256)
    // For elliptic, we can pass the string as an array of bytes, and it hashes it internally,
    // or we can explicitly hash it. Here we use the built-in hash.
    const signature = this.keyPair.sign(payloadString);
    
    // 2. Return the signature as a hex string
    return signature.toDER('hex');
  }

  /**
   * Get the public key in hex format to send to the backend during enrollment.
   */
  public getPublicKey(): string {
    return this.keyPair.getPublic('hex');
  }
}

export const cryptoSigner = new CryptoSigner();
